spring.application.name=Numy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

vaadin.productionMode=true
spring.datasource.url=jdbc:mysql://localhost:3306/numy?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=santi
spring.datasource.password=2007absalom
server.port=3050
spring.devtools.restart.poll-interval=1000ms
spring.devtools.restart.quiet-period=100ms
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
com.vaadin=INFO

logging.level.org.springframework=INFO
logging.level.com.numy=DEBUG
jwt.secret=defaultSecretKey123456789012345678901234567890
jwt.expiration=3600000
spring.mvc.enabled=false
logging.level.ROOT=INFO